alias: Turn off the kettle after 7 minutes
trigger:
  platform: state
  entity_id: switch.kitchen__kettle
  to: 'on'
  for:
    minutes: 7
action:
  service: homeassistant.turn_off
  entity_id: switch.kitchen__kettle