- platform: wake_on_lan
  mac_address: "40-8D-5C-58-D8-6A"
  host: !secret IP_desktop
  name: Computer - Desktop
  turn_off:

- platform: wake_on_lan
  mac_address: "BC-AE-C5-95-16-DE"
  host: !secret IP_server
  name: Computer - Server
  turn_off:
  
- platform: wake_on_lan
  mac_address: "00-00-00-00-00-00"
  host: !secret IP_laptop
  name: Computer - Laptop
  turn_off:
  
- platform: wake_on_lan
  mac_address: "00-00-00-00-00-00"
  host: !secret IP_tablet
  name: Computer - Tablet
  turn_off:

- platform: template
  switches:
    xbox:
      value_template: "{% if is_state('media_player.xbox_one', 'on') %}on{% else %}off{% endif %}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.xbox_one
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.xbox_one

- platform: tellstick