alias: Turn on main lights when Popeen gets home
trigger:
  platform: state
  entity_id: device_tracker.popeensphone
  from: 'not_home'
  to: 'home'
condition:
  condition: sun
  after: sunset
  after_offset: "-1:00:00"
action:
  service: homeassistant.turn_on
  entity_id: group.mainlights